name: Update Readme with Metrics

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      # lets you manually trigger the workflow

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
